version: "3.5"

services:

  nginx:
    build: ./nginx
    ports:
      - 8080:8080
    depends_on:
      - django
    volumes:
      - ./static:/var/www/static
    networks:
      backend:

  django:
    container_name: dj_asana
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "gunicorn src.wsgi:application -b 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - ./static:/app/static
    expose:
      - "8000"
    networks:
      backend:
        aliases:
          - django
    depends_on:
      - postgres

  postgres:
    image: postgres:11-alpine
    container_name: dj_asana_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=asana
    expose:
      - "5432"
    networks:
      backend:
        aliases:
          - postgres

networks:
  backend:
    name: backend
