# Generated by Django 3.0.6 on 2020-05-20 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsanaProject',
            fields=[
                ('gid', models.CharField(max_length=31, primary_key=True, serialize=False, verbose_name='Globally unique identifier')),
                ('name', models.CharField(max_length=255, verbose_name='Project name')),
            ],
        ),
        migrations.CreateModel(
            name='AsanaUser',
            fields=[
                ('gid', models.CharField(max_length=31, primary_key=True, serialize=False, verbose_name='Globally unique identifier')),
                ('name', models.CharField(max_length=255, verbose_name='Full name')),
            ],
        ),
        migrations.CreateModel(
            name='AsanaTask',
            fields=[
                ('gid', models.CharField(max_length=31, primary_key=True, serialize=False, verbose_name='Globally unique identifier')),
                ('name', models.TextField(verbose_name='Task name')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='dj_asana.AsanaUser', verbose_name='Assignee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dj_asana.AsanaProject', verbose_name='Project')),
            ],
        ),
    ]
